"""Standalone approval gate for SENSITIVE operations.

Design — why this cannot be self-approved by the agents
-------------------------------------------------------
Approval is a **public-key signature** problem, not a password problem.

  * A human holds an Ed25519 **private** key (generated by ``tools/gen_keys.py``,
    stored only on the human's machine, never in Secret Manager, never in any
    deployed environment).
  * The Master and every worker hold only the Ed25519 **public** key. This
    ``ApprovalGate`` object has *no field, method, or import* that can produce
    a signature — by construction it can only *verify* one.
  * To approve a request you must sign that request's unique nonce. Only the
    private-key holder can do that. A fully compromised Master or worker still
    cannot forge an approval, because it does not possess the private key.

That is the real guarantee. Python code can always be monkeypatched in-process,
so the protection is a **key-possession boundary** enforced by IAM and process
isolation, not by trying to make Python tamper-proof. The deployed service
accounts are provisioned so they cannot read the private key; see the README.

Behaviour
---------
``request_approval`` BLOCKS indefinitely. There is no timeout, no auto-approve,
no bulk-approve: each request carries its own nonce and needs its own signature.
If no public key is configured the gate FAILS CLOSED — sensitive operations
cannot proceed at all.
"""

from __future__ import annotations

import base64
import os
import sys
import time
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

from .logging_utils import get_logger
from .schemas import ApprovalRequest, ApprovalStatus
from .state_store import StateStore

log = get_logger("agentmgr.approval_gate")

_CANONICAL_PREFIX = "agentmgr-approval:v1"


# --- exceptions ----------------------------------------------------------

class ApprovalDenied(RuntimeError):
    """The human signed a denial for this request."""


class ApprovalNotProvisioned(RuntimeError):
    """No approval public key configured — fail closed; cannot proceed."""


# --- sensitivity classification -----------------------------------------

class SensitiveCategory(str, Enum):
    FILESYSTEM_OUTSIDE_WORKDIR = "filesystem_outside_workdir"
    CREDENTIAL_ACCESS = "credential_access"
    GOOGLE_API = "google_account_api"
    SPEND_OVER_THRESHOLD = "spend_over_threshold"


_CREDENTIAL_HINTS = (
    "credential", "secret", "token", "password", "api_key", "apikey",
    "2fa", "mfa", "otp", "private_key", "privkey",
)
_GOOGLE_HINTS = ("google", "gmail", "gdrive", "google_drive", "gcal", "calendar")


@dataclass(frozen=True)
class ApprovalDecision:
    approved: bool
    request_id: str
    note: str = ""


def canonical_message(request_id: str, nonce: str, decision: str) -> bytes:
    """The exact bytes a human must sign to approve/deny a request."""
    return f"{_CANONICAL_PREFIX}:{request_id}:{nonce}:{decision}".encode("utf-8")


def load_public_key(public_key_b64: str) -> Ed25519PublicKey:
    return Ed25519PublicKey.from_public_bytes(base64.b64decode(public_key_b64))


def verify_signature(
    public_key: Ed25519PublicKey,
    request_id: str,
    nonce: str,
    decision: str,
    signature_b64: str,
) -> bool:
    """True iff ``signature_b64`` is a valid Ed25519 signature for the request."""
    if decision not in ("approve", "deny"):
        return False
    try:
        signature = base64.b64decode(signature_b64)
    except Exception:  # noqa: BLE001 - any decode failure is just "invalid"
        return False
    try:
        public_key.verify(signature, canonical_message(request_id, nonce, decision))
        return True
    except InvalidSignature:
        return False


class ApprovalGate:
    """Blocks a SENSITIVE operation until a human cryptographically approves it.

    This object holds only a *public* key. It can verify approvals; it cannot
    create them.
    """

    def __init__(
        self,
        store: StateStore,
        *,
        public_key_b64: str | None,
        channel: str = "store",
        poll_interval_s: float = 1.0,
        workdir: str | None = None,
        spend_threshold_usd: float = 5.0,
        rp_id: str = "localhost",
        origin: str = "http://localhost:8080",
    ) -> None:
        self._store = store
        self._channel = channel
        self._poll_interval_s = poll_interval_s
        self._workdir = Path(workdir or os.getcwd()).resolve()
        self._spend_threshold_usd = spend_threshold_usd
        self._rp_id = rp_id          # for verifying passkey (webauthn) proofs
        self._origin = origin
        # The ONLY key material on this object is a public key. There is
        # deliberately no private-key attribute and no signing method.
        self._public_key: Ed25519PublicKey | None = (
            load_public_key(public_key_b64) if public_key_b64 else None
        )

    # --- classification --------------------------------------------------

    def classify(self, action: str, details: dict[str, Any]) -> SensitiveCategory | None:
        """Return the SENSITIVE category for an operation, or None if benign.

        SENSITIVE (per the security spec) = filesystem access outside the job's
        own working directory; access to credentials / tokens / 2FA-MFA
        material; any Google account API call; any spend above threshold.
        """
        haystack = " ".join(
            [action.lower(), " ".join(str(k).lower() for k in details)]
        )

        if any(hint in haystack for hint in _GOOGLE_HINTS):
            return SensitiveCategory.GOOGLE_API
        if any(hint in haystack for hint in _CREDENTIAL_HINTS):
            return SensitiveCategory.CREDENTIAL_ACCESS

        spend = details.get("spend_usd")
        if isinstance(spend, (int, float)) and spend > self._spend_threshold_usd:
            return SensitiveCategory.SPEND_OVER_THRESHOLD

        path = details.get("path")
        if path is not None:
            resolved = Path(str(path)).resolve()
            if not resolved.is_relative_to(self._workdir):
                return SensitiveCategory.FILESYSTEM_OUTSIDE_WORKDIR

        return None

    # --- the gate --------------------------------------------------------

    def guard(self, action: str, details: dict[str, Any]) -> ApprovalDecision | None:
        """Classify an operation; if SENSITIVE, block on human approval.

        Returns None for benign operations (no approval needed), an approved
        :class:`ApprovalDecision` once a human signs off, or raises
        :class:`ApprovalDenied`.
        """
        category = self.classify(action, details)
        if category is None:
            return None
        return self.request_approval(
            action, details, sensitive_reason=category.value
        )

    def request_approval(
        self,
        action: str,
        details: dict[str, Any],
        *,
        sensitive_reason: str = "explicit",
    ) -> ApprovalDecision:
        """Persist an approval request and BLOCK until a human signs it.

        No timeout. No auto-approve. No bulk-approve.
        """
        if self._public_key is None and not self._store.list_passkeys():
            # Fail closed: with neither an Ed25519 key nor a registered passkey
            # there is no way to verify an approval.
            raise ApprovalNotProvisioned(
                "approval gate has no verifier (no Ed25519 public key and no "
                "registered passkey); SENSITIVE operations cannot proceed"
            )

        request = ApprovalRequest(
            action=action,
            details={**details, "_sensitive_reason": sensitive_reason},
        )
        self._store.put_approval(request)
        log.info(
            "approval requested — BLOCKING for human signature",
            extra={
                "approval_id": request.id,
                "action": action,
                "sensitive_reason": sensitive_reason,
            },
        )
        self._announce(request)

        seen_bad: set[str] = set()
        while True:
            current = self._store.get_approval(request.id)
            response = current.response if current else None
            if response is not None:
                if self._verify_response(request, response):
                    return self._finalize(request, response.decision)
                marker = repr(sorted(response.model_dump().items()))
                if marker not in seen_bad:
                    seen_bad.add(marker)
                    log.warning(
                        "rejected an INVALID approval proof; still blocking",
                        extra={"approval_id": request.id},
                    )
            time.sleep(self._poll_interval_s)

    def _verify_response(self, request: ApprovalRequest, response) -> bool:
        """Verify an approval response — Ed25519 signature OR passkey assertion.

        Both proof types are verified HERE, in the gate, against material the
        gate already holds (public key / registered credential). The gate never
        takes the Master's word that an approval is valid.
        """
        if response.proof_type == "webauthn":
            if not response.webauthn_assertion:
                return False
            from .passkey import challenge_for, verify_assertion

            expected = challenge_for(
                canonical_message(request.id, request.nonce, response.decision)
            )
            return verify_assertion(
                self._store, response.webauthn_assertion, expected,
                self._rp_id, self._origin,
            )
        # default: Ed25519 signature
        if self._public_key is None:
            return False
        return verify_signature(
            self._public_key, request.id, request.nonce,
            response.decision, response.signature_b64,
        )

    def _finalize(self, request: ApprovalRequest, decision: str) -> ApprovalDecision:
        if decision == "approve":
            self._store.set_approval_status(request.id, ApprovalStatus.APPROVED)
            log.info("approval GRANTED", extra={"approval_id": request.id})
            return ApprovalDecision(approved=True, request_id=request.id)
        self._store.set_approval_status(request.id, ApprovalStatus.DENIED)
        log.info("approval DENIED", extra={"approval_id": request.id})
        raise ApprovalDenied(f"approval {request.id} was denied by the operator")

    def _announce(self, request: ApprovalRequest) -> None:
        """Tell the operator a request is waiting.

        A deployed Cloud Run Service/Job has no interactive terminal, so the
        operator approves from *their own* terminal by running
        ``python -m tools.approve``. When the gate itself runs in a TTY
        (local dev) we print the instructions inline.
        """
        if self._channel == "stdin" and sys.stdin.isatty():
            sys.stdout.write(
                f"\n=== APPROVAL REQUIRED ===\n"
                f"  id:     {request.id}\n"
                f"  action: {request.action}\n"
                f"  reason: {request.details.get('_sensitive_reason')}\n"
                f"  Approve in a terminal:  python -m tools.approve\n"
                f"=========================\n"
            )
            sys.stdout.flush()
